#!/bin/bash

msg="Siga os passos para criar um script: \n\n

Execute o programa usando './create' \n
Passe como parâmetro o nome do seu script seguindo as boas práticas: \n\n

./create nomeScript\n\n

- nomescript\n
- nomeScript\n
- nome_script\n
- nome-script\n
\n

Lembrete: scripts em bash não levam em consideração a extensão do arquivo. \n
"

[[ $# -ne 1 ]] && echo -e $msg && exit 1

> $1
echo '#!/bin/bash' > $1
chmod +x $1
echo '' >> $1
echo '# Script criado utilizando o script-creator! Obrigado pelo apoio.' >> $1
echo '# Autor: martinsdevv' >> $1
echo '' >> $1
echo 'echo "Hello, World!"' >> $1
echo 'exit 0' >> $1

nano $1

exit 0

